project: 
  type: website
  output-dir: docs
  
  
website: 
  title: "Stat 515 Website"
  navbar: 
   left:
      - href: Intro.qmd
        text: Home
      - href: hello.qmd
        text: about


format:
  html:
    theme: solar
    css: styles.css
    toc: true